#!/bin/bash
puppet resource package git ensure=present
puppet resource package apache2 ensure=present
puppet resource service apache2 ensure=running
puppet resource file /21050672/script_dir clone ensure=absent force=true
puppet resource file /21050672/script_dir ensure=directory
puppet resource file /21050672/script_dir clone ensure=directory
cd /21050672/script_dir
git clone https:// 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@github.com/kash78/21050672_repo.git
cp -p /21050672/script_dir/index.html /var/www/html
